### ISSUE TITLE
Globbing broken in linux release

### ISSUE THREAD

**Issue by kribor** [leonid-shevtsov/split_tests#7]
To try this out I downloaded latest linux binary and tried on ubuntu 22.04 and 20.04 inside of docker. Globbing is apparently completely broken as -glob only ever catches one single file...

Very basic test trying to catch 2 `.sh` files with glob failing: 
```
split_tests -split-index 0 -split-total 1 -glob *.sh
get-reg-token.sh 
docker@1e97446d7fdf:/$ ls *.sh
get-reg-token.sh  start.sh
```

I expect to get all files when using split total 1 and index 0. Am I missing something obvious here?

**Comment by ryanong** [comment]
Argument command parsing here is weird. I've been running into similar issues. Make sure to quote your globs otherwise they are expanded before being sent as an argument

**Comment by leonid-shevtsov** [comment]
Hey, sorry for the late response. Yeah it's a typical situation with shell expansions. If you pass `*.sh` as an argument to any command, it will get expanded by the shell before the command receives it.

I could implement consuming of all arguments, and resolve this, but IMO it's better to explicitly quote the argument and allow the internal globber to do the work, because it keeps behavior consistent:

```sh
split_tests -split-index 0 -split-total 1 -glob '*.sh'
```

I'll update the readme.
